### ISSUE TITLE
The filename option is required

### ISSUE THREAD

**Issue by daviddiasfront** [symdiff/symdiff-jade#1]
Running symdiff-jade I have this error :

```
the "filename" option is required to use "include" with "relative" paths
```

I know that is a jade option who normally can be specified, but I don't know how to specify that with simdiff-jade.

**Comment by prayerslayer** [comment]
Hah. Yes. When you look at the code you’ll see that everything `symdiff-jade` does is rendering it to HTML and passing off to `symdiff-html`. Of course that breaks once you need configuration options.

I’ll check if [`jade-parser`](https://github.com/jadejs/jade-parser) is ready for the task yet, wasn’t last time I did.

**Comment by prayerslayer** [comment]
`0.0.3` now uses `jade-lexer` and `jade-parser`, please open a new issue if you have problems.
