### ISSUE TITLE
Fails to walk the entire Jade AST

### ISSUE THREAD

**Issue by baileyparker** [symdiff/symdiff-jade#3]
symdiff-jade no longer walks the complete AST of a jade file (in fact, it doesn't get past the html tag) anyone due to a change in the structure of the AST. The `walk()` function seems to expect that there is a `nodes` property on every object (and if not it bails). However, the AST syntax for jade now has blocks, which aggregate nodes. If the node has children, it has a block property with a block object containing its children.

So the AST now looks like this:

    { type: 'Block',
      nodes:
       [ { type: 'Doctype', val: 'html', line: 1 },
         { type: 'Tag',
           name: 'html',
           selfClosing: false,
           block: { type: 'Block',
                    nodes:
                      [ [Object],
                        [Object],
                        [Object],
                        [Object],
                        [Object],
                        [Object],
                        [Object],
                        [Object],
                        [Object],
                        [Object] ] },
           attrs: [],
           attributeBlocks: [],
           isInline: false,
           line: 2 } ],
      line: 0 }

I can PR a quick fix for this.

**Comment by prayerslayer** [comment]
First, thanks for reporting and creating a PR.

But before I merge it I’d like to understand the root cause here. Did this happen with the 0.0.3 update of symdiff-jade? Did something else change? With which file content did you encounter this problem?

**Comment by baileyparker** [comment]
As far as I can tell, this has been present since the initial version of Jade.

Children are pushed to `node.block.nodes` if the block don't only contain text: https://github.com/jadejs/jade-parser/commit/a57c56c552449880707ec7e40272103b7a644231#diff-168726dbe96b3ce427e7fedce31bb0bcR687

And it seems like the AST object for type `Tag` never had a `nodes` property: https://github.com/jadejs/jade-parser/commit/a57c56c552449880707ec7e40272103b7a644231#diff-168726dbe96b3ce427e7fedce31bb0bcR577

I believe the tests were misleading. I'd venture a guess that because they were only testing single lines of jade (not nested at all), the extraction currently on master was working because the AST contained one node of type `Tag` that had a class attribute. If the tests used more realistic jade like:

```jade
html
  body
    div.grid
      div.grid-col
```

They would fail.

I've updated the tests on #4 (CI failed due to coverage—I'm fixing that now—but the tests work) and created a branch on my fork to demonstrate the tests failing on the current master with real jade: baileyparker/symdiff-jade@e0137066977ebfe55a5c435130dda136132ae5d7.
