### ISSUE TITLE
Incorrect handling of conditional classes (js in jade class attributes)

### ISSUE THREAD

**Issue by baileyparker** [symdiff/symdiff-jade#5]
In jade it's possible to conditionally add classes using javascript:

```jade
div.will-always-have-this-one(class=(Math.random() < 0.5 ? 'but-not-always-this-one' : ''))
```

symdiff-jade just treats the entire JS expression as a class. This is a difficult case to handle because given arbitrary javascript it's impossible to always conceive every possible output.

The trouble is that if `.but-not-always-this-one` is referenced in the CSS but nowhere else in the jade, it's possible that symdiff would report that `.but-not-always-this-one` is not used.

However, there might be a way to distinguish this type of class attribute from one of the css-selector-like ones (`div.stuff`). In which case, perhaps a warning that some classes can't be extracted listing the JS expressions would benefit the user (this way they could visually confirm that `.but-not-always-this-one` is actually used and not mistakenly remove it from the CSS). Maybe something like:

    [Warning] Some elements contain conditional classes, which can cause classes to be incorrectly reported as unused:
        file.jade:23
        |  div(class=(Math.random() < 0.5 ? 'but-not-always-this-one' : ''))

**Comment by prayerslayer** [comment]
Yeah, back with `gulp-check-unused-css` I had basically the same problem in Angular because you can put arbitrary JS stuff in `ng-class`. I "solved" it by supporting only the ternary operator there. Would this be sufficient here too?

In any case a warning would be nice, I agree.

**Comment by baileyparker** [comment]
I imagine there wouldn't be many other expressions commonly included than the ternary, so yes, that should suffice.

Are you thinking of emitting a warning for any case that the class attribute doesn't match `/\s*\.-?[_a-zA-Z]+[_a-zA-Z0-9-]*\s*/` ([What characters are valid in CSS class names/selectors?[http://stackoverflow.com/questions/448981/what-characters-are-valid-in-css-class-names-selectors])? Or only for those that don't match that regex and we can't parse a ternary out of them?

**Comment by prayerslayer** [comment]
I will have to wrap my head around warnings, because there is currently no concept for that in symdiff. Of course one could just use `console`, but then they won’t be nicely formatted. Probably that’s a separate issue.

In my opinion we should emit warnings for class expressions we can’t properly parse ternary expressions out of.
